# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-31 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20191031_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='expiration_datetime',
        ),
    ]
